# Generated by Django 6.1 on 2026-08-18 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_email', models.EmailField(help_text='Must end in .edu or university domain', max_length=254, unique=True)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Licensed Clinical Psychologist', max_length=150)),
                ('specialization', models.CharField(default='Anxiety, Depression, Trauma, Life Transitions', max_length=255)),
                ('bio', models.TextField(blank=True, default='Compassionate, evidence-based therapy tailored to your unique journey.')),
                ('avatar_color', models.CharField(default='#5B9EA7', max_length=20)),
                ('availability', models.JSONField(blank=True, default=dict, help_text='e.g. {"monday": "9-5", "tuesday": "9-5"}')),
                ('is_accepting_clients', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
