# Generated by Django 6.1 on 2026-08-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='therapists/'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='photo_url',
            field=models.URLField(blank=True, default='', help_text='External image link or static path if not uploading'),
        ),
        migrations.AlterField(
            model_name='studentverification',
            name='edu_email',
            field=models.EmailField(help_text='Must end in .edu, .edu.ng, or university domain', max_length=254, unique=True),
        ),
    ]
