# Generated by Django 6.1 on 2026-08-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('core', 'Core Sessions'), ('packages', 'Packages & Bundles'), ('student', 'Student Offers'), ('mental_health', 'Mental Health & Wellness'), ('memberships', 'Memberships'), ('addons', 'Add-Ons')], default='core', max_length=30)),
                ('offer_type', models.CharField(choices=[('single', 'Single Session'), ('package', 'Package / Bundle'), ('assessment', 'Assessment'), ('group', 'Group Session'), ('intensive', 'Day Intensive'), ('membership', 'Membership'), ('addon', 'Add-On')], default='single', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_student_offer', models.BooleanField(default=False)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration in minutes (e.g. 50, 90, 240)', null=True)),
                ('sessions_included', models.IntegerField(default=1, help_text='Number of sessions included in package')),
                ('badge', models.CharField(blank=True, help_text='e.g. Student, Bestseller, New, Package, Sale', max_length=50)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, help_text='Line-separated list of key benefits')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
