# Generated by Django 6.1 on 2026-08-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, help_text='Offer cover image or illustration', null=True, upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='badge',
            field=models.CharField(blank=True, help_text='e.g. Student, Bestseller, New, Package, Save 20%', max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original before-discount price in ₦', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Nigerian Naira (₦)', max_digits=12),
        ),
    ]
