# Generated by Django 6.1 on 2026-08-18 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, help_text='Session appointment start date and time', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Auto-calculated based on offer duration', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('client_notes', models.TextField(blank=True, help_text='Special requests or focus areas from the client')),
                ('meeting_link', models.URLField(blank=True, default='', help_text='Virtual room or clinic location info')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bookings', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='offers.offer')),
                ('therapist', models.ForeignKey(blank=True, help_text='Assigned therapist or counselor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapist_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time', '-created_at'],
            },
        ),
    ]
